---
- hosts: webservers 
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "apache2"
        state: "latest"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: true
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
