---
- hosts: webservers
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: myweb
        image: "kelvinduan/webapp:latest"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
